
#Modify game mechanics based on dimensions
[cleansedDimensions]
	#EXPERIMENTAL! MUST BE ALL CHARACTERS FROM [a-z0-9/._-] OR THE GAME WILL CRASH. List the dimension names that you want the following configs to interact with. (e.g. the_bumblezone:the_bumblezone,minecraft:overworld
	infectionDimensionCleanse = "notadimension"
	#Disables hostile mob attack based infections in cleansed dimensions
	hostileInfectInCleanse = true
	#Disables player attack based infections in cleansed dimensions
	playerInfectInCleanse = false
	#Disables raw food infections in cleansed dimensions
	rawFoodInfectedInCleanse = true

